import {onDocumentWritten} from "firebase-functions/v2/firestore";
import * as logger from "firebase-functions/logger";

import {db} from "../admin";
import {sendPush} from "../messaging";

/**
 * Real-time push trigger — fires whenever the on-device Orchestrator pins a
 * new message to `dashboard_pins/{uid}`. Used for instant alerts that cannot
 * wait for a scheduled tick:
 *   - Glycemic Guardian Red-score alerts
 *   - Coaching suggestions after a meal log
 *   - Plan-ready notifications
 *
 * Why a write trigger and not onCreate? The orchestrator overwrites the
 * single document on every new pin (see `AgentTools.pinToDashboard`), so the
 * lifecycle is "updates" not "creates" after the first write.
 */
export const onDashboardPinChanged = onDocumentWritten(
  {
    document: "dashboard_pins/{userId}",
    region: "europe-west1",
  },
  async (event) => {
    const userId = event.params.userId;
    const after = event.data?.after?.data();
    const before = event.data?.before?.data();
    if (!after) return; // Deletion — nothing to push.

    // Only push if the pin id changed (i.e. it's a fresh message),
    // or if the message body changed.
    const sameMessage =
      before?.pinId === after.pinId && before?.message === after.message;
    if (sameMessage) return;

    // Don't push for low-severity info pins generated by the AppOpened
    // handler — only push high-signal events. Tune this list as needed.
    const pushTypes = new Set([
      "glycemic_alert",
      "morning_briefing",
      "midday_check",
      "evening_summary",
      "weekly_review",
      "meal_reminder",
      "plan_ready",
      "coaching_tip",
    ]);
    if (!pushTypes.has(after.type)) return;

    const userDoc = await db.collection("users").doc(userId).get();
    const token = userDoc.data()?.fcmToken as string | undefined;
    if (!token) return;

    const title = titleFor(after.type as string);
    const body = (after.message as string | undefined) ?? title;
    logger.info("dashboard_pin -> FCM", {userId, type: after.type});

    await sendPush(token, {
      title,
      body,
      type: after.type as string,
      pinId: after.pinId as string | undefined,
    });
  },
);

function titleFor(type: string): string {
  switch (type) {
    case "glycemic_alert":
      return "FitAI — Glycemic alert";
    case "morning_briefing":
      return "FitAI — Morning briefing";
    case "midday_check":
      return "FitAI — Midday check";
    case "evening_summary":
      return "FitAI — Evening summary";
    case "weekly_review":
      return "FitAI — Weekly review";
    case "meal_reminder":
      return "FitAI — Meal reminder";
    case "plan_ready":
      return "FitAI — Plan ready";
    case "coaching_tip":
      return "FitAI — Coaching tip";
    default:
      return "FitAI";
  }
}
